import React from "react";
import FileItem from "../components/FileItem";
import Container from "../components/Container";

const data = [
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
  {
    _id: "678a62592bc1a3a5d25a7fcd",
    filePath:
      "uploads/678a6018a02d2892c35adf6a/document-1737122391521-895370890.pdf",
    fileType: "application/pdf",
    userId: "678a6018a02d2892c35adf6a",
    fileName: "my file",
    originalText:
      "\n\nGaurav Rana\nFullstack\nDeveloper\nHow to reach me:\nCell: \nEmail:\nLinkedin: \nGithub:\n+919729343885\ngaurav.ranaji96@gmail.com\n@gauravrana96\nhttps://github.com/smartgauravrana\nProfessional Skills\nCoding Languages: \nFrameworks/Systems: \nJavaScript, C#, HTML/CSS, \nASP.NET Core\nReactJs, NodeJs, Typescript,\nGraphql, Nextjs, Tailwind CSS,\nWebpack, Visual Studio\nCareer Summary\nFull Stack Developer\nPersonal Profile\nI am a Fullstack\ndeveloper with robust\nproblem-solving skills\nand proven experience\nin creating and\ndesigning software in a\ntest-driven environment.\nEducational Training\nPanipat Institue of\nEngineering and Technology\nGraduated on May 2019\nBachelor of Technology in\nComputer Science\nProjects Summary\nNykaa Network\nA community engagement\nplatform.\nHandled backend and\nfrontend functionality.\nMercadolar\nA currency exchange\nplatform\nWorked on Frontend with\nReact and nodejs as backend,\nDatabases:\nMongoDb, SQL\nAddress:\n59, RK Puram, Karnal\nCloud:\nAWS Services for Serverless\napps, Cloudformation, Batch Job\nHealthCare Project \nInsurance and Health care\nmanagement.\nWorked on AWS Serverless\nfor backend.\nPentair IOT Products\nWorked on AWS Services for\nIOT Products.\nWorked on GoLang and\nNodejs with Serverless\nArchitecture\nAirtel Gaming\nA platform similar to twitch\nbut specially made for the\nindian audience.\nHandled backend and web\nfrontend functionality.\nAWS Lambdas, S3, SQS, SNS\nfor serverless apps\nDeveloping resuable UI\ncomponents\nDeveloping REST api and\ndefining schema for\ndatabase.\nIntegrating api on frontend\npart\nDaffodil Software\nJan 2019 to Jan 2021\nSourcefuse Technologies\nJan 2021 to March 2022\nDeveloping serverless\napplications.\nWriting cloudformation\ntemplates for cloud\nresources\nAirtel Digital Ltd\nMarch 2022 to Jan 2023\nDeveloping REST APIs as per\nPRD.\nCreating web platform similar\nto android gaming app.\nTerrascope\nCarbon measurement and\nmanagement tool.\nLeveraged materialised\nviews, and aws batch jobs to\nreduce measurement time\nfrom 6 hrs to 40 mins\nWorked on new features and\ntroubleshoot production\nincidents.\nTerrascope\nFeb 2023 to Present\nPerformance Optimisation for\nexisting workflows.\nWorked on new features.\nProduction Support",
    summary: {
      short:
        "Gaurav Rana is a Full Stack Developer with expertise in various coding languages and frameworks like JavaScript, ReactJs, and ASP.NET Core. He has worked on diverse projects such as Nykaa Network and Airtel Gaming, showcasing skills in backend and frontend development using technologies like AWS Services and Nodejs. His experience includes roles at Daffodil Software, Sourcefuse Technologies, and Airtel Digital Ltd, focusing on serverless applications, REST APIs, and cloud resources management. Currently, he is involved in performance optimization and new feature development at Terrascope.",
      _id: "678a62592bc1a3a5d25a7fce",
      medium:
        "Gaurav Rana is a Full Stack Developer showcasing expertise in various coding languages and frameworks such as JavaScript, C#, ReactJs, and ASP.NET Core. With a Bachelor's degree in Computer Science, he has engaged in diverse projects like Nykaa Network and Mercadolar, demonstrating skills in backend and frontend development. Rana has a robust background in utilizing AWS services for serverless applications and cloud resources, evident in projects like Pentair IOT Products and Airtel Gaming. His recent work at Terrascope involves performance optimization and new feature development, underscoring a continuous commitment to enhancing existing workflows and providing production support in a problem-solving environment.",
      long: "The text provides a detailed profile of Gaurav Rana, a Full Stack Developer, showcasing his contact information, professional skills, career summary, educational background, and project experience. Gaurav specializes in coding languages like JavaScript, C#, and HTML/CSS, along with frameworks like ReactJs and NodeJs. His career summary highlights his problem-solving abilities and software development experience in a test-driven environment. Educational training includes a Bachelor of Technology in Computer Science from Panipat Institute of Engineering and Technology in May 2019.\n\nIn terms of projects, Gaurav has worked on various platforms such as Nykaa Network, Mercadolar, Pentair IOT Products, Airtel Gaming, and Terrascope, showcasing his expertise in backend and frontend development, utilizing technologies like AWS Services, MongoDB, SQL, and serverless architecture. His work at Sourcefuse Technologies and Airtel Digital Ltd involved developing serverless applications, writing cloud formation templates, creating REST APIs, and building web platforms. Notably, in Terrascope, he optimized existing workflows, reduced carbon measurement time significantly, and provided production support.\n\nOverall, Gaurav Rana's profile demonstrates a strong technical background, hands-on experience in diverse projects, and a proactive approach to problem-solving and innovation in software development, making him a seasoned Full Stack Developer with expertise in a range of technologies and frameworks.",
    },
    createdAt: "2025-01-17T13:59:53.741Z",
    updatedAt: "2025-01-17T14:05:16.922Z",
  },
];

const Files = () => {
  return (
    <Container>
      <div>
        <div className="m-4">
          <span className="text-lg font-semibold mr-2 inline-block">
            Upload new file to generate summary:
          </span>{" "}
          <button className="btn btn-neutral"> Upload </button>
        </div>
        {data.map(({ fileName, createdAt, _id }) => (
          <FileItem
            key={_id}
            fileId={_id}
            fileName={fileName}
            createdAt={createdAt}
          />
        ))}
      </div>
    </Container>
  );
};

export default Files;
